#ifndef __CODE_GEN_H__
#define __CODE_GEN_H__

#include "../inc/parser.h"

#ifdef __cplusplus
extern "C" {
#endif

#define SYPHERIZE_HEADER "This file was auto-generated by Sypherize."
#define INT_STR_WIDTH 21

typedef enum TargetType {
    TARGET_DEFAULT = 0,
    TARGET_X86_64_AT_T_ASM,
} TargetType;

void choose_target(TargetType target, ParsingContext *context,
                   AstNode *program_node);

void write_bytes(char *byte_str, FILE *fptr);

void write_line(char *byte_str, FILE *fptr);

void write_int(long int_val, FILE *fptr);

void write_header(FILE *fptr);

void target_x86_64_att_asm_data_section(ParsingContext *context, FILE *fptr);

void target_x86_64_att_asm_expr_windows(ParsingContext *context,
                                        AstNode *curr_expr,
                                        FILE *fptr_code_gen);

void target_x86_64_att_asm_func_windows(ParsingContext *context,
                                        char *func_name, AstNode *func,
                                        FILE *fptr_code_gen);

void target_x86_64_att_asm_windows(ParsingContext *context,
                                   AstNode *program_node);

#ifdef __cplusplus
}
#endif

#endif /* __CODE_GEN_H__ */
